### ISSUE TITLE
v0.8.5 generates invalid PNGs

### ISSUE THREAD

**Issue by lovasoa** [image-rs/deflate-rs#48]
I'm opening this issue because updating deflate from 0.8.4 to 0.8.5 in [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) makes the tests fail. deflate is an indirect dependency of this project, used to generate and read PNG files. 

The following image is a PNG created with png v0.16.6 and deflate v0.8.5 which cannot be opened with the same libraries : 
 
![err](https://user-images.githubusercontent.com/552629/86540623-1ff44580-bf07-11ea-8ed5-8dbc3bab5fb2.png)

The error returned is :  `CorruptFlateStream`.

Running the same code (generating and reading the PNG) with png v0.16.6 and deflate v0.8.**4** works without errors.

**Comment by oyvindln** [comment]
Hm, seems my fix for #47 may have broken something.

**Comment by oyvindln** [comment]
I've yanked 0.8.5 for now, can you check if 6c97e51 fixes the issue? I made changes that will hopefully fix this without re-introducing #47. I wasn't sure what the source for the you used as an example was here, but the commit did prevent the same issue happening when running dezoomify-rs on https://artsandculture.google.com/asset/light-in-the-dark/ZQFouDGMVmsI2w  (using level 2, lower levels didn't trigger it) which was linked in the readme.

**Comment by lovasoa** [comment]
Thanks, I am going to test this. The example image I gave comes from the test suite; you can just run cargo test to reproduce the error.

**Comment by lovasoa** [comment]
The failing test is the one that runs `dezoomify-rs  --retries 0 'testdata/generic/map_{{X}}_{{Y}}.jpg' /tmp/out.png`

**Comment by lovasoa** [comment]
I just ran the test, and 6c97e5143df139af578cdd884e0dee9940414ea1 indeed fixes the issue.


The test passes with:

```toml
[patch.crates-io]
deflate = {git="https://github.com/image-rs/deflate-rs",rev="6c97e5143df139af578cdd884e0dee9940414ea1"}
```

and it fails with : 

```toml
[patch.crates-io]
deflate = {git="https://github.com/image-rs/deflate-rs",rev="fcbe4206c45cf55d80ae8feb94f0613fe795659f"}
```
